version: '3.8'  # Убедитесь, что используете актуальную версию

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile  # Укажите путь к вашему Dockerfile для бэкенда
    env_file:
      - .env  # Укажите файл .env здесь
    ports:
      - "5000:5000"  # Порт, на котором будет работать бэкенд
    depends_on:
      - db  # Укажите зависимости, если есть

  frontend:
    build:
      context: ./frontend  # Укажите путь к папке с фронтендом
      dockerfile: Dockerfile  # Укажите путь к вашему Dockerfile для фронтенда
    ports:
      - "3000:3000"  # Порт, на котором будет работать фронтенд

  db:
    image: postgres:latest  # Укажите образ для базы данных
    environment:
      POSTGRES_USER: ${DB_USERNAME}  # Используйте переменные из .env
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"  # Порт для доступа к базе данных