services:
  db:
    image: postgres:latest
    container_name: dapp-for-business_db_1
    networks:
      - dapp-for-business_dapp-network
    environment:
      POSTGRES_USER: Alex
      POSTGRES_PASSWORD: avtb140985
      POSTGRES_DB: HB3A
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Alex -d HB3A"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    image: node:16
    container_name: dapp-node
    networks:
      - dapp-for-business_dapp-network
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://Alex:avtb140985@db:5432/HB3A
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app
    command: "node server.js"

  frontend:
    build:
      context: ./frontend
    image: node:16
    container_name: dapp-frontend
    networks:
      - dapp-for-business_dapp-network
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: "npm start"

volumes:
  postgres-data:
  grafana-data:

networks:
  dapp-for-business_dapp-network:
    external: true
