version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: dapp-for-business_db_1
    networks:
      dapp-network:
        aliases:
          - database
    environment:
      POSTGRES_USER: Alex
      POSTGRES_PASSWORD: avtb140985
      POSTGRES_DB: HB3A
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: .
    image: node:16
    container_name: dapp-node
    networks:
      dapp-network:
        aliases:
          - backend
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://Alex:avtb140985@db:5432/HB3A
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app
    command: "node server.js"

  frontend:
    build:
      context: ./frontend
    image: node:16
    container_name: dapp-frontend
    networks:
      dapp-network:
        aliases:
          - frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: "npm start"

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    networks:
      - monitoring
    volumes:
      - grafana-data:/var/lib/grafana

networks:
  dapp-network:
    driver: bridge
  monitoring:
    driver: bridge

volumes:
  postgres-data:
  grafana-data:
