version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dapp-backend
    # Подключаем файл с переменными окружения для сервера (секретные данные, ключи БД и т.д.)
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    # Если backend зависит от работы БД, можно добавить depends_on:
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dapp-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:14
    container_name: dapp-db
    restart: always
    environment:
      POSTGRES_USER: "Alex"
      POSTGRES_PASSWORD: "avtb140985"
      POSTGRES_DB: "HB3A"
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: